### ISSUE TITLE
Docker volumes on macOS

### ISSUE THREAD

**Issue by davock** [indrawp/Setup-Guide#3]
If you are using a mac machine to run your server the following won't work in most cases: 

```
 volumes:
      - ./redis_slave:/data 
```

because in mac only some folders are allowed for mounting docker volumes.  I propose to add something like this to the documentation 

## For macOS users

If yor server is macOs you are limited to specific folders to mount docker volumes, so for example
the volume on "./redis_master:/data" may not be mounted and produce an error since the relative path "./" is not likely to be included in the inclusion list.
In order set up the volumes properly refer to:
https://docs.docker.com/docker-for-mac/osxfs/#namespaces

**Comment by indrawp** [comment]
Thanks for the proposal, I will add this to the readme
